// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-_VN8edivHrRv5xd9QVgnYv-pV1Rl0WI',
    appId: '1:724141443535:web:eada6c562a8f679026eaba',
    messagingSenderId: '724141443535',
    projectId: 'whatsapp-new-clone-3fa2b',
    authDomain: 'whatsapp-new-clone-3fa2b.firebaseapp.com',
    databaseURL: 'https://whatsapp-new-clone-3fa2b-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-new-clone-3fa2b.appspot.com',
    measurementId: 'G-L3LR8LLGB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJou1wH1xCqCPu-9yUpVcXuMOOduCShY',
    appId: '1:724141443535:android:a43ce45f8f9617f826eaba',
    messagingSenderId: '724141443535',
    projectId: 'whatsapp-new-clone-3fa2b',
    databaseURL: 'https://whatsapp-new-clone-3fa2b-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-new-clone-3fa2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClZNaP9NVYF18N3gVMCqW81ElLsds8mLk',
    appId: '1:724141443535:ios:49f4e3770f2b8dd626eaba',
    messagingSenderId: '724141443535',
    projectId: 'whatsapp-new-clone-3fa2b',
    databaseURL: 'https://whatsapp-new-clone-3fa2b-default-rtdb.firebaseio.com',
    storageBucket: 'whatsapp-new-clone-3fa2b.appspot.com',
    iosBundleId: 'com.example.mplMini',
  );
}
